[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
line_length=120
multi_line_output=3
include_trailing_comma="True"
use_parentheses="True"
force_grid_wrap=0

[tool.unimport]
exclude='(__init__.py)|venv|env'
remove="True"

[tool.semantic_release]
version_variables = ['src/setup.py:__version__']
tag_format = '{version}'
commit_parser = "angular"
changelog_file = "CHANGELOG.md"
branch = "main"
build_command = "make compile build"
dist_path = "src/dist/"
upload_to_repository = false
